### PR TITLE
Add SCSS support and extra variables

### PR DESCRIPTION
**Pull request by pajter**
- Add SCSS output
- Add theming variables
- Add grid-base variable
- Add missing JS output categories
- Output components to SCSS, CSS, JS

Currently WUI doesn't use any of the components variables. Are these completely up to date, and can/should WUI start applying those? If yes, ideally I'd like to have these variables for every component going forward.

On a side note: when I get to migrating the Page component to WUI, I'm going to see if I can implement https://jamonserrano.github.io/plumber-sass/. This makes it a lot easier to get proper vertical rhythm based on font family and its cap-height. No need to do all those cumbersome calculations manually. Just set up the config that gives us the desired design, and add those variables to the dictionary. If you then need to change the base font-size or a ratio, we just update those variables instead of manually recalculating all the related font-sizes and paddings etc.  What do you think?

### CODE REVIEW

**Comment by kimhart** [comment]
You are so quick!! This looks awesome — glad to have the grid & theming added, too. As far as the components go, John was going a little rogue working on that by himself so I'm not certain what state it's in. We'd have to test and make sure that his stuff matches the latest designs. I don't see why WUI wouldn't be able to inherit them, except that it may make quick style updates slower if we have to update both projects?

**Comment by pajter** [comment]
> I don't see why WUI wouldn't be able to inherit them, except that it may make quick style updates slower if we have to update both projects?

That's a good point! I'll leave that up to you and Monica. It would depend on how often you want to change those things.

Having decent automation in place for releasing new versions would really help speed that up though.

**Comment by monibons** [comment]
Thanks for the quick PR @pajter !

I would rather deprecate John's component variables since they were created in somewhat of a vacuum and, like Kim said, it would change our current workflow for making style adjustments quickly and easily and potentially create more overheard than is necessary.

**Comment by pajter** [comment]
@monibons You got it!

**Comment by pajter** [comment]
@kimhart @monibons Any objections to also adding `font-display: swap` to avoid FOIT?

**Comment by monibons** [comment]
@pajter How about `fallback` instead? I personally hate when sites load unstyled fonts first so I'd like to give it a chance to try to load the custom font first and fallback if downloading the font takes too long. Thoughts?

**Comment by pajter** [comment]
@monibons Sure, that's perfectly fine with me.

**Comment by pajter** [comment]
Done! I have nothing more to add for now. 😄

**Comment by pajter** [comment]
@monibons @kimhart Any blockers remaining on merging this?

**Comment by kimhart** [comment]
@pajter I don't think so! Sorry for the lag. I believe most of our projects are locked to a specific version of Hook so doing a release shouldn't be an issue. I'll get this up now.

**Pull request merged**
