### PR TITLE
Remove unused Overpass font weights

### PR DESCRIPTION
**Pull request by CharlieDieter**

### CODE REVIEW

**Comment by monibons** [comment]
@CharlieDieter are you sure you don't want to include some font weights between `regular` and `extrabold`? Seems like a big gap and it might be safer to include `semibold` and a `medium` so you guys have more flexibility, thoughts?

**Comment by CharlieDieter** [comment]
@monibons I wondered that as well, but Adam was sure that Lato would fill those gaps.

**Comment by monibons** [comment]
Okay if you guys are sure you won't need them we can go ahead and merge this in.

**Comment by monibons** [comment]
@CharlieDieter can you add `Overpass` to the font.yaml file? It won't output to the `fonts.less` file unless you do.

**Comment by CharlieDieter** [comment]
Oo my bad. On it now.

**Pull request merged**
