### PR TITLE
Add primary and secondary button component values

### PR DESCRIPTION
**Pull request by radium-v**
* Adds `alpha-fade` values to allow for alpha colors in buttons
* Removes the `size/rem` conversion

### CODE REVIEW

**Comment by radium-v** [comment]
@kimhart Yeah, I kept seeing both sets of values in the comps. This really matters most when the `dark` and `light` variations come into play.

**Comment by kimhart** [comment]
Cool! I guess we just have to clearly document when to use which one. Looks good!

**Comment by pajter** [comment]
Good stuff, very organized! 👍

I'm just wondering if it would make sense to shift the order for components like so:

```less
@ds-button-secondary-color-background-dark-disabled: rgba(0, 0, 0, 0);
@ds-button-secondary-color-border-light-static: #2f3542;
@ds-button-primary-color-text: #ffffff;
@ds-button-size-border-radius: 0.1875rem;
```

I'm thinking if you're writing component CSS, you would start typing `@ds-button-` and see all variables in that namespace instead of having to search through the top-level `@ds-color` or `@ds-size`, etc. categories. I feel that would improve DX and align with how the YAML files are structured too.

I'd love to hear your thoughts on this.

**Comment by radium-v** [comment]
@pajter @kimhart Here's the `design-library-extensions` module that uses these directly: https://github.com/jwplayer/design-library-extensions/blob/198d46f7740ac074c4d6f1d01d83412b72fee606/ds-components/src/button/button.less

I agree that it does seem quite off after sleeping on it. Even though it follows the C/T/I structure as suggested by `style-dictionary`, it doesn't really work here. I'll look at the `attribute/cti` transform and see if we can't fudge it for just modules.

**Pull request merged**
